### ISSUE TITLE
How to change the location of .env

### ISSUE THREAD

**Issue by brajmohans** [appstract/laravel-elixir-env#4]
How can I override default path for .env file?

**Comment by ovanschie** [comment]
This will be implemented in the next release.

**Comment by ovanschie** [comment]
In the newest version you can use:
```javascript
require('laravel-elixir-env').config({ path: 'my-folder/.env' });
```

**Comment by pkimtani** [comment]
Hi, I tried to overrite the env file using config-path as descibed above (and in the docs), but in my console I am still getting data from the default env. When I run gulp, it says found .env and found ./myEnv (the overriden env). How do I override the default env completely so that it's not loaded at the first place. Thank you

**Comment by ovanschie** [comment]
@pkimtani this package is not supported anymore. Laravel Mix supports it by default now
https://laravel.com/docs/5.6/mix#environment-variables
